version: '3'

services:
  puppeteer:
    image: puppeteer:latest
    build:
      context: .
      dockerfile: tests/Dockerfile.test
    command: npm test
    links:
    - backend
    - frontend
    - test_database
    volumes:
    - ./tests/reports:/home/app/tests/reports
    depends_on:
      backend:
        condition: service_healthy
    stdin_open: true
    tty: true

  backend:
#    command: bash
#    stdin_open: true
#    tty: true
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/healthcheck"]
      interval: 2s
      retries: 10
    links:
    - test_database
    environment:
      APP_DATABASE_URL: mysql://root:password@test_database:3306/estoque

  frontend:
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:80/healthcheck" ]
      interval: 2s
      retries: 10

  test_database:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: estoque
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3307:3306
